"""
Phase 0 validation harness.

The old backtest asked "did it fire before the break on eight names I already
knew broke." That question cannot fail informatively. This one can.

What was missing and is now here:

  1. A CONTROL GROUP. `backtest_v2.json` reported FPR 0.288 with no
     control-construction code in the repo at all. Cases are now GENERATED
     across the whole admissible universe by `build_cases()`: a filer whose
     filings show a fundamental deterioration event is a positive, one that
     never does is a control. Nothing is hand-picked, so there is no hindsight
     selection and no survivorship step to get wrong.

  2. A TUNING/HOLDOUT SPLIT, written to disk and hashed before any threshold is
     chosen. v2's Z_TRIGGER, weight table and THRESHOLD=45 were all set while
     looking at the same eight cases whose lead times were then reported.

  3. CENSORING DETECTION. WBD and LUMN "fired" at 2019-02-15, the first cutoff
     in the window, and that was reported as +42mo and +45mo of lead. The true
     first fire is before the data starts. Censored cases are excluded from the
     median lead rather than credited with it.

  4. A PRE-REGISTERED DECISION RULE with a written kill condition, committed
     before the run.

Point-in-time discipline is enforced upstream: the scorer passed in here is
`signals_v3.evaluate`, which truncates on the XBRL `filed` date.
"""
from __future__ import annotations

import hashlib
import json
import os
import random
from dataclasses import asdict, dataclass, field
from datetime import date
from statistics import median
from typing import Any

MAX_CREDITABLE_LEAD_MONTHS = 24
TUNING_FRACTION = 0.55

DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
SPLIT_PATH = os.path.join(DATA, "split.json")
PREREG_PATH = os.path.join(DATA, "prereg.json")
CASES_PATH = os.path.join(DATA, "cases.json")


# ------------------------------------------------------------------- cases


@dataclass
class Case:
    ticker: str
    cik: str
    label: str
    is_positive: bool
    regime: str                 # macro regime, e.g. "2021-22-growth-unwind"
    broke: str | None = None    # YYYY-MM; required for positives
    # The date the break became PUBLIC -- the first-vintage filing date of the
    # quarter that tripped the label. PREREG["notes"] requires lead to be
    # measured to this, not to the period end; harness had no field to carry it
    # and measured to the period instead, which recorded a filer that fired one
    # month before publication as having fired AFTER the break.
    broke_filed: str | None = None
    sector: str = ""
    cap_decile: int | None = None

    @staticmethod
    def from_dict(d: dict) -> Case:
        return Case(**d)


def load_cases() -> list[Case]:
    """Case registry. Positives AND controls live in one file so the split can
    stratify across both."""
    with open(CASES_PATH) as fh:
        return [Case.from_dict(d) for d in json.load(fh)["cases"]]


def load_split(which: str) -> list[Case]:
    """Cases for one split, read from the frozen records inside split.json.

    Never from cases.json: that file is regenerated by `ledgerline cases` and
    is not covered by any hash the old code checked, so a regeneration between
    committing the split and scoring it silently changed the labels. Reading a
    ticker the split names but has no frozen record for is a hard error rather
    than a quiet short return.
    """
    if which not in ("tuning", "holdout"):
        raise ValueError("split must be 'tuning' or 'holdout'")
    verify_split()
    with open(SPLIT_PATH) as fh:
        payload = json.load(fh)
    frozen = payload.get("cases") or {}
    tickers = list(payload[which])
    missing = [t for t in tickers if t not in frozen]
    if missing:
        raise RuntimeError(
            f"split.json lists {len(missing)} ticker(s) with no frozen case "
            f"record: {missing[:10]}. The split is unusable."
        )
    return [Case.from_dict(frozen[t]) for t in tickers]


# ------------------------------------------------------------------ outcomes


@dataclass
class Outcome:
    ticker: str
    is_positive: bool
    fired: bool
    censored: bool
    first_fire: str | None
    lead_months: int | None
    fire_rate: float
    scoreable_quarters: int
    flags: list[str] = field(default_factory=list)
    regime: str | None = None
    # Kept last so the positional constructor used throughout the tests is
    # unaffected. Counts firing quarters, which the per-quarter FPR needs and
    # fire_rate cannot supply without rounding back through the denominator.
    n_fires: int = 0


def months_between(a: str, b: str) -> int:
    """Signed months from a to b. Positive means a precedes b -- a lead."""
    return (int(b[:4]) - int(a[:4])) * 12 + (int(b[5:7]) - int(a[5:7]))


def evaluate_case(case: Case, cutoffs: list[str], scorer, threshold: float) -> Outcome:
    """`scorer(ticker, cik, as_of) -> dict | None`.

    One code path for backtest and production. If they diverge, the backtest
    measures something the product does not do.
    """
    scores: list[float] = []
    first, first_flags, first_scoreable = None, [], None
    for c in cutoffs:
        res = scorer(case.ticker, case.cik, as_of=c)
        if not res or not res.get("scoreable") or res.get("score") is None:
            continue
        if first_scoreable is None:
            first_scoreable = c
        scores.append(res["score"])
        if res["score"] >= threshold and first is None:
            first = c
            first_flags = [f["code"] for f in res.get("flags", [])]

    # Firing on the first cutoff at which the filer was scoreable at all means
    # the true first fire is outside the window. Report it, do not credit it.
    censored = first is not None and first == first_scoreable

    # Lead is measured to the date the break became PUBLIC, per PREREG["notes"],
    # falling back to the period only for cases built before broke_filed existed.
    target = case.broke_filed or case.broke
    lead = None
    if first and target and not censored:
        lead = months_between(first[:7], target[:7])
        # An unbounded lead credits a fire years early as detection. A filer
        # that fired once at its second-ever scoreable cutoff and never again
        # scored a 108-month lead and counted as a hit. Only a fire inside the
        # pre-registered horizon is detection; anything earlier is unrelated.
        if not 0 < lead <= MAX_CREDITABLE_LEAD_MONTHS:
            lead = None

    return Outcome(
        ticker=case.ticker,
        is_positive=case.is_positive,
        fired=first is not None,
        censored=censored,
        first_fire=first,
        lead_months=lead,
        fire_rate=(sum(1 for s in scores if s >= threshold) / len(scores)) if scores else 0.0,
        scoreable_quarters=len(scores),
        n_fires=sum(1 for s in scores if s >= threshold),
        flags=first_flags,
        regime=case.regime,
    )


# -------------------------------------------------------------------- splits


def make_split(seed: int, tuning_frac: float = TUNING_FRACTION) -> dict:
    """Deterministic split, stratified by regime and by positive/control, then
    written to disk and hashed. Commit the hash before running anything. If the
    hash changes, the holdout is burned."""
    if os.path.exists(SPLIT_PATH):
        raise RuntimeError(
            "split.json already exists -- re-rolling the split lets it be "
            "redrawn until the holdout looks favourable, which is the same "
            "burn as editing it. Delete it deliberately and record why."
        )
    cases = load_cases()
    rng = random.Random(seed)
    strata: dict[tuple[str, bool], list[Case]] = {}
    for c in cases:
        strata.setdefault((c.regime, c.is_positive), []).append(c)

    n_pos = sum(1 for c in cases if c.is_positive)
    n_neg = len(cases) - n_pos
    max_frac_neg = 1 - (PREREG["min_controls"] / n_neg) if n_neg else 0.0
    max_frac_pos = 1 - (PREREG["min_positives"] / n_pos) if n_pos else 0.0
    ceiling = min(max_frac_neg, max_frac_pos)
    if ceiling <= 0:
        raise RuntimeError(
            f"case set cannot satisfy the pre-registered holdout minimums "
            f"({PREREG['min_positives']} positives, {PREREG['min_controls']} "
            f"controls) at any split: have {n_pos} positives, {n_neg} controls"
        )
    if tuning_frac > ceiling:
        # The holdout is what verdict() scores, so it is the side that has to
        # satisfy the counts. At 0.60 the shipped set left 186 holdout controls
        # against a floor of 200 and the run was a guaranteed KILL.
        tuning_frac = round(ceiling - 0.005, 3)

    tuning, holdout = [], []
    for key in sorted(strata, key=lambda k: (k[0], k[1])):
        group = sorted(strata[key], key=lambda c: c.ticker)
        rng.shuffle(group)
        cut = round(len(group) * tuning_frac)
        # A stratum of one would otherwise land entirely in tuning and the
        # holdout would silently lose that regime.
        if len(group) > 1:
            cut = min(max(cut, 1), len(group) - 1)
        tuning += group[:cut]
        holdout += group[cut:]

    h_pos = sum(1 for c in holdout if c.is_positive)
    h_neg = len(holdout) - h_pos
    if h_pos < PREREG["min_positives"] or h_neg < PREREG["min_controls"]:
        raise RuntimeError(
            f"holdout would be {h_pos} positives / {h_neg} controls, below the "
            f"pre-registered {PREREG['min_positives']} / {PREREG['min_controls']}"
        )

    payload = {
        "seed": seed,
        "created": date.today().isoformat(),
        "tuning_frac": tuning_frac,
        "tuning": sorted(c.ticker for c in tuning),
        "holdout": sorted(c.ticker for c in holdout),
        # Frozen BY VALUE, not by reference. The hash used to cover only the
        # ticker lists, while load_split() re-read cases.json at scoring time
        # to recover is_positive, broke and regime. Flipping 30 holdout
        # positives to controls in cases.json changed the scored set from
        # 192/186 to 162/191 with verify_split() still returning green -- and
        # `broke`, the denominator of every lead measurement, was equally
        # unprotected.
        "cases": {c.ticker: asdict(c) for c in sorted(tuning + holdout,
                                                      key=lambda c: c.ticker)},
        # Binds the split to the rule it was drawn under.
        "prereg_sha256": prereg_hash(),
    }
    payload["sha256"] = _hash(payload)
    os.makedirs(DATA, exist_ok=True)
    with open(SPLIT_PATH, "w") as fh:
        json.dump(payload, fh, indent=2)
    return payload


def _hash(payload: dict) -> str:
    body = {k: v for k, v in payload.items() if k != "sha256"}
    return hashlib.sha256(json.dumps(body, sort_keys=True).encode()).hexdigest()


def verify_split() -> str:
    """Recompute the hash. Raises if the split was edited after commit."""
    with open(SPLIT_PATH) as fh:
        payload = json.load(fh)
    if payload.get("sha256") != _hash(payload):
        raise RuntimeError("split.json modified after commit -- the holdout is burned")
    return payload["sha256"]


# ------------------------------------------- pre-registered decision rule

PREREG: dict[str, Any] = {
    "label": "fundamental_deterioration_2of5_within_4q",
    # PRIMARY false-positive measure: control filer-QUARTERS that fire.
    #
    # The per-filer "ever fired" rate was the original rule, but controls average
    # 43 scoreable cutoffs each, so "<=10% of controls ever fire" silently
    # demands a <=0.24% per-quarter rate -- one false fire per 409 control
    # filer-quarters. That is a far harsher bar than the number reads as, and it
    # is not comparable across filers with different amounts of history.
    #
    # 0.04 is derived from the product's own cost model, not from the data.
    # ROADMAP §8 requires narration volume of "a handful per day across the
    # universe". At ~1500 filers x 4 filings/year that is ~6000 filer-quarters,
    # or ~23.8 per business day; 4% of those gating in is ~0.95 false
    # narrations per business day. (The earlier 0.05 was stated as "well under
    # one per day" and actually implies ~1.2, so the comment and the number
    # disagreed -- corrected here rather than left to be discovered later.)
    # Chosen before the split, from the spec rather than from a run.
    "max_false_positive_rate_per_quarter": 0.04,
    # Reported alongside, NOT pass/fail -- see above.
    "report_false_positive_rate_per_filer": True,
    "min_median_lead_months": 6,
    "min_positive_hit_rate": 0.60,
    "must_beat_baseline": "ttm_ocf_negative_and_net_debt_positive",
    "min_positives": 40,
    "min_controls": 200,
    # Applies to the HOLDOUT, which is what verdict() measures. The default
    # 60/40 split of the shipped case set left 186 holdout controls against a
    # floor of 200, so the one-shot run returned KILL for a provably perfect
    # gate. make_split() now solves for a fraction that satisfies both sides.
    "min_controls_scope": "holdout",
    # An unbounded lead credits a fire years before the break as detection.
    "max_creditable_lead_months": 24,
    # Censored positives are excluded from the median lead; they are excluded
    # from the hit-rate denominator too, rather than silently counted as misses.
    "censored_treatment": "excluded_from_both",
    "min_regimes": 4,
    "regime_window": "2011-2025",
    "excluded_sectors": "SIC 6000-6599, 6700-6799 (financials, real estate, REITs)",
    "kill_if_any_fails": True,
    "notes": (
        "Lead is measured from the gate's fire date to the FILING date of the "
        "quarter that tripped the deterioration label, not to the period end. "
        "A quarter ending 3/31 is not public until it is filed. Price drawdown "
        "is reported but is not part of the rule."
    ),
}


def write_prereg() -> dict:
    """Call once, commit the file, then do not touch it."""
    if os.path.exists(PREREG_PATH):
        raise RuntimeError("prereg.json already exists -- rewriting it voids the test")
    os.makedirs(DATA, exist_ok=True)
    payload = {"committed": date.today().isoformat(), "rule": PREREG}
    with open(PREREG_PATH, "w") as fh:
        json.dump(payload, fh, indent=2)
    return payload


def load_prereg() -> dict:
    """The committed rule, read from disk.

    verdict() used to index the module-level PREREG dict, which nothing ever
    compared against prereg.json. Editing the constant in place turned a KILL
    into a SHIP on identical outcomes while the committed file still read the
    original thresholds -- the pre-registration was decorative.
    """
    if not os.path.exists(PREREG_PATH):
        raise RuntimeError(
            "prereg.json is missing -- the decision rule must be committed "
            "before a split is scored. Run `ledgerline prereg`."
        )
    with open(PREREG_PATH) as fh:
        rule = json.load(fh)["rule"]
    drift = {k for k in set(rule) | set(PREREG)
             if rule.get(k) != PREREG.get(k)}
    if drift:
        raise RuntimeError(
            "prereg.json disagrees with harness.PREREG on "
            f"{sorted(drift)} -- the committed rule is the rule. Revert the "
            "module or start a new pre-registration; do not edit either to "
            "match the other after a split exists."
        )
    return rule


def prereg_hash() -> str:
    """Hash of the committed rule, so a split can be bound to it."""
    return hashlib.sha256(
        json.dumps(PREREG, sort_keys=True, default=str).encode()
    ).hexdigest()


def verdict(outcomes: list[Outcome], baseline_fpr: float | None = None) -> dict:
    """Apply the pre-registered rule. Run on the HOLDOUT, exactly once."""
    rule = load_prereg()
    pos = [o for o in outcomes if o.is_positive]
    neg = [o for o in outcomes if not o.is_positive]

    fpr_filer = (sum(1 for o in neg if o.fired) / len(neg)) if neg else None
    ctrl_q = sum(o.scoreable_quarters for o in neg)
    fpr = (sum(o.n_fires for o in neg) / ctrl_q) if ctrl_q else None
    leads = [o.lead_months for o in pos if o.lead_months is not None]
    # Censored positives are excluded from the median lead, so counting them as
    # misses in the denominator here punished the gate twice for a case it was
    # never able to be assessed on. Excluded from both, and reported.
    assessable = [o for o in pos if not o.censored]
    n_led = sum(1 for o in assessable if o.lead_months and o.lead_months > 0)
    hit_rate = (n_led / len(assessable)) if assessable else 0.0
    med_lead = median(leads) if leads else None

    checks = {
        "false_positive_rate_per_quarter": {
            "value": None if fpr is None else round(fpr, 4),
            "limit": rule["max_false_positive_rate_per_quarter"],
            "pass": fpr is not None and fpr <= rule["max_false_positive_rate_per_quarter"],
        },
        "median_lead_months": {
            "value": med_lead,
            "limit": rule["min_median_lead_months"],
            "pass": med_lead is not None and med_lead >= rule["min_median_lead_months"],
        },
        "positive_hit_rate": {
            "value": round(hit_rate, 3),
            "limit": rule["min_positive_hit_rate"],
            "pass": hit_rate >= rule["min_positive_hit_rate"],
        },
    }
    # Regimes in which the gate actually fired with lead, not regimes merely
    # PRESENT among holdout positives. Presence is a property of the case set,
    # so the old check could not fail -- which made it unable to detect the
    # beta detector it exists to catch: a gate that only works in one falling
    # market would still show 6 regimes "covered".
    regimes = {o.regime for o in outcomes
               if o.is_positive and o.regime and o.fired
               and (o.lead_months or 0) > 0}
    regimes_present = {o.regime for o in outcomes if o.is_positive and o.regime}
    checks["regime_coverage"] = {
        "value": len(regimes),
        "limit": rule["min_regimes"],
        "pass": len(regimes) >= rule["min_regimes"],
    }
    checks["sample_size"] = {
        "value": {"positives": len(pos), "controls": len(neg)},
        "limit": {"positives": rule["min_positives"], "controls": rule["min_controls"]},
        "pass": len(pos) >= rule["min_positives"] and len(neg) >= rule["min_controls"],
    }
    # Fails CLOSED. The check used to be added only when baseline_fpr was
    # supplied, and backtest.run() never supplied it -- so a criterion the rule
    # requires was silently absent, and `all(...)` over the remaining checks
    # could not tell a missing criterion from a passing one.
    if rule.get("must_beat_baseline"):
        checks["beats_naive_baseline"] = {
            "value": fpr if baseline_fpr is not None else "NOT COMPUTED",
            "limit": baseline_fpr if baseline_fpr is not None
            else rule["must_beat_baseline"],
            "pass": baseline_fpr is not None and fpr is not None
            and fpr < baseline_fpr,
        }

    passed = all(c["pass"] for c in checks.values())
    return {
        "checks": checks,
        # Reported, never gated on: the fraction of control FILERS that fired at
        # least once. Kept visible because one false alert per company may be
        # what actually costs trust, even when the per-quarter rate is fine.
        "false_positive_rate_per_filer": None if fpr_filer is None else round(fpr_filer, 4),
        "control_filer_quarters": ctrl_q,
        "n_positive": len(pos),
        "n_control": len(neg),
        "n_censored": sum(1 for o in outcomes if o.censored),
        "regimes_detected": sorted(regimes),
        "regimes_present": sorted(regimes_present),
        "n_censored_positives": sum(1 for o in pos if o.censored),
        "n_assessable_positives": len(assessable),
        "verdict": "SHIP" if passed else "KILL",
        "note": (
            "All pre-registered criteria met on holdout."
            if passed
            else "At least one pre-registered criterion failed. Per prereg.json the "
                 "deterministic gate is not a viable product core. Write up the "
                 "finding; do not retune and re-run against this holdout."
        ),
    }


def outcomes_to_dicts(outcomes: list[Outcome]) -> list[dict]:
    return [asdict(o) for o in outcomes]


# ------------------------------------------------------- generated case set


def build_cases(tickers: dict[str, str], sic_lookup=None, normalizer=None) -> dict:
    """Generate the case registry across the admissible universe.

    `tickers` is {ticker: cik}. `sic_lookup(cik) -> str|None` and
    `normalizer(cik) -> dict` are injected so this is testable without network.

    A filer is a POSITIVE if its filings show a fundamental deterioration event
    (label.first_deterioration); a CONTROL if it never does. Nothing is curated.
    That is the whole point -- eight names remembered as blowups cannot produce
    a control group, cannot be split, and carry hindsight selection that no
    amount of downstream statistics repairs.

    Every rejection is recorded with its reason. A silently dropped filer is a
    survivorship bias with extra steps.
    """
    from .. import edgar as _edgar
    from .. import label as _label
    from .. import signals as _signals
    from .. import universe as _universe

    sic_lookup = sic_lookup or _universe.fetch_sic
    normalizer = normalizer or _edgar.normalize

    cases, rejected = [], []
    for ticker, cik in sorted(tickers.items()):
        norm = normalizer(cik)
        sic = sic_lookup(cik)
        # Anchor the search at the filer's own first scoreable cutoff, so an
        # early break does not discard the later ones the gate could be tested on.
        start = _universe.scoreable_from(norm) if norm else None
        broke = _label.first_deterioration(ticker, cik, norm, not_before=start) if norm else None

        ok, reason = _universe.admit(cik, ticker, norm, sic, broke=broke)
        if not ok:
            rejected.append({"ticker": ticker, "cik": cik, "reason": reason})
            continue

        regime = _universe.regime_for(broke) if broke else None
        # The date the break became public. Lead is measured against this, per
        # PREREG["notes"] -- not against the period end, which is 4-6 weeks
        # earlier and made a gate that fired before publication look late.
        broke_filed = None
        if broke:
            period = next(
                (r["end"] for r in _signals.series(norm, "revenue", "Q")
                 if r["end"][:7] == broke), None,
            )
            if period:
                broke_filed = _label.broke_date_filed(norm, period)
        cases.append(
            Case(
                ticker=ticker,
                cik=cik,
                label=f"{ticker} deterioration {broke}" if broke else f"{ticker} control",
                is_positive=bool(broke),
                broke=broke,
                broke_filed=broke_filed,
                regime=regime or "control",
                sector=str(sic or ""),
            )
        )

    payload = {
        "generated": date.today().isoformat(),
        "label_rule": PREREG["label"],
        "n_positive": sum(1 for c in cases if c.is_positive),
        "n_control": sum(1 for c in cases if not c.is_positive),
        "regimes": sorted({c.regime for c in cases if c.is_positive}),
        "cases": [asdict(c) for c in cases],
        "rejected": rejected,
    }
    os.makedirs(DATA, exist_ok=True)
    with open(CASES_PATH, "w") as fh:
        json.dump(payload, fh, indent=2)
    return payload


def readiness(cases_payload: dict | None = None) -> dict:
    """Is the case set big and broad enough to build a split from?

    Called before make_split so a split is never built on a set that cannot
    satisfy the pre-registered rule anyway.
    """
    if cases_payload is None:
        with open(CASES_PATH) as fh:
            cases_payload = json.load(fh)
    cases = [Case.from_dict(c) for c in cases_payload["cases"]]
    pos = [c for c in cases if c.is_positive]
    neg = [c for c in cases if not c.is_positive]
    regimes = {c.regime for c in pos}
    # readiness() runs BEFORE prereg.json exists (it gates `ledgerline split`,
    # which gates `ledgerline prereg`), so it reads the module constant. Only
    # verdict() -- which scores the holdout -- reads the committed file.
    #
    # The counts are checked against what the HOLDOUT will receive, not against
    # the full case set. Checking the full set is what let a split be written
    # that made the pre-registered rule unsatisfiable.
    frac = 1 - TUNING_FRACTION
    h_pos, h_neg = round(len(pos) * frac), round(len(neg) * frac)
    checks = {
        "positives": {"value": len(pos), "limit": PREREG["min_positives"],
                      "pass": len(pos) >= PREREG["min_positives"]},
        "controls": {"value": len(neg), "limit": PREREG["min_controls"],
                     "pass": len(neg) >= PREREG["min_controls"]},
        "regimes": {"value": sorted(regimes), "limit": PREREG["min_regimes"],
                    "pass": len(regimes) >= PREREG["min_regimes"]},
        "holdout_positives": {"value": h_pos, "limit": PREREG["min_positives"],
                              "pass": h_pos >= PREREG["min_positives"]},
        "holdout_controls": {"value": h_neg, "limit": PREREG["min_controls"],
                             "pass": h_neg >= PREREG["min_controls"]},
    }
    return {"ready": all(c["pass"] for c in checks.values()), "checks": checks}
